import { defineField, defineType } from "sanity";

export const siteSettingsType = defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  fields: [
    defineField({
      name: "heroTitle",
      title: "Hero Title",
      type: "string",
      description: "Main headline on the home page",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroBadge",
      title: "Hero Badge",
      type: "string",
      description: 'Small badge shown above the hero title, e.g. "AutoCeive Coming Soon"',
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "image",
      options: { hotspot: true },
      description: "Main image shown on the right side of the hero section",
    }),
    defineField({
      name: "heroSubtitle",
      title: "Hero Subtitle",
      type: "string",
      description: "Secondary headline below the main title",
    }),
    defineField({
      name: "heroDescription",
      title: "Hero Description",
      type: "text",
      rows: 3,
      description: "Short paragraph shown in the hero section",
    }),
    defineField({
      name: "heroPrimaryCtaLabel",
      title: "Hero Primary CTA Label",
      type: "string",
      description: 'Primary hero button text, e.g. "Explore Products"',
    }),
    defineField({
      name: "heroSecondaryCtaLabel",
      title: "Hero Secondary CTA Label",
      type: "string",
      description: 'Secondary hero button text, e.g. "Contact Us"',
    }),
    defineField({
      name: "siteName",
      title: "Site Name",
      type: "string",
      description: 'Used for organization details, e.g. "FAR Better Bio"',
    }),
    defineField({
      name: "logoText",
      title: "Logo Text",
      type: "string",
      description: 'Short brand text shown beside the logo, e.g. "FAR Better"',
    }),
    defineField({
      name: "siteDescription",
      title: "Site Description",
      type: "text",
      rows: 3,
      description: "Short brand description used in the footer and structured data",
    }),
    defineField({
      name: "productsLabel",
      title: "Products Section — Eyebrow Label",
      type: "string",
      description: 'Small text above the heading, e.g. "FAR: Filtrate Alternate Return"',
    }),
    defineField({
      name: "productsHeading",
      title: "Products Section — Heading",
      type: "string",
      description: 'Main heading, e.g. "Cell-Targeted Blood Processing"',
    }),
    defineField({
      name: "productsDescription",
      title: "Products Section — Description",
      type: "text",
      rows: 3,
      description: "Paragraph shown below the products heading on the home page",
    }),
    defineField({
      name: "labSuppliesCalloutHeading",
      title: "Lab Supplies Callout — Heading",
      type: "string",
      description: 'e.g. "Looking for laboratory supplies?"',
    }),
    defineField({
      name: "labSuppliesCalloutDescription",
      title: "Lab Supplies Callout — Description",
      type: "string",
      description: "One-line text below the callout heading",
    }),
    defineField({
      name: "productsCtaLabel",
      title: "Products Section — CTA Label",
      type: "string",
      description: 'Button text for the products callout, e.g. "Browse Products"',
    }),
    defineField({
      name: "servicesLabel",
      title: "Services Section — Eyebrow Label",
      type: "string",
      description: 'Small text above the heading, e.g. "Our Services"',
    }),
    defineField({
      name: "servicesHeading",
      title: "Services Section — Heading",
      type: "string",
      description: 'Main heading, e.g. "Professional Laboratory Services"',
    }),
    defineField({
      name: "servicesDescription",
      title: "Services Section — Description",
      type: "text",
      rows: 3,
      description: "Paragraph shown below the services heading on the home page",
    }),
    defineField({
      name: "servicesInlineIntro",
      title: "Services Section — Inline Link Line Intro",
      type: "string",
      description: 'Text before first link, e.g. "See our"',
    }),
    defineField({
      name: "servicesInlinePrimaryLabel",
      title: "Services Section — Inline Primary Link Label",
      type: "string",
      description: 'e.g. "apheresis and aferez-focused product portfolio"',
    }),
    defineField({
      name: "servicesInlinePrimaryHref",
      title: "Services Section — Inline Primary Link Href",
      type: "string",
      initialValue: "/products",
    }),
    defineField({
      name: "servicesInlineMiddle",
      title: "Services Section — Inline Middle Text",
      type: "string",
      description: 'Text between links, e.g. "or"',
    }),
    defineField({
      name: "servicesInlineSecondaryLabel",
      title: "Services Section — Inline Secondary Link Label",
      type: "string",
      description: 'e.g. "contact our Turkiye-based biomedical team"',
    }),
    defineField({
      name: "servicesInlineSecondaryHref",
      title: "Services Section — Inline Secondary Link Href",
      type: "string",
      initialValue: "/contact",
    }),
    defineField({
      name: "servicesInlineOutro",
      title: "Services Section — Inline Link Line Outro",
      type: "string",
      description:
        'Text after second link, e.g. "for manufacturer and R&D collaboration inquiries."',
    }),
    defineField({
      name: "servicesCtaLabel",
      title: "Services Section — CTA Label",
      type: "string",
      description: 'Button text below the services list, e.g. "Learn More About Our Services"',
    }),
    defineField({
      name: "quoteText",
      title: "Quote Section — Quote Text",
      type: "text",
      rows: 4,
      description: "Main quote shown near the bottom of the home page",
    }),
    defineField({
      name: "quoteAttribution",
      title: "Quote Section — Attribution",
      type: "string",
      description: 'e.g. "CEO, FAR Better"',
    }),
    defineField({
      name: "quoteCtaHeading",
      title: "Quote Section — CTA Heading",
      type: "string",
      description: 'Heading above the contact CTA, e.g. "What do you need?"',
    }),
    defineField({
      name: "quoteCtaDescription",
      title: "Quote Section — CTA Description",
      type: "text",
      rows: 3,
      description: "Supporting text shown above the contact button",
    }),
    defineField({
      name: "quoteCtaButtonLabel",
      title: "Quote Section — CTA Button Label",
      type: "string",
      description: 'Button text for the quote section CTA, e.g. "Contact Us"',
    }),
    defineField({
      name: "locationName",
      title: "Location Name",
      type: "string",
      description: 'Displayed near the embedded map, e.g. "ODTÜ Bilim ve İnovasyon Merkezi"',
    }),
    defineField({
      name: "googleMapsEmbedUrl",
      title: "Google Maps Embed URL",
      type: "url",
      description: "Embed URL used on the contact page map iframe",
    }),
    defineField({
      name: "googleMapsOpenUrl",
      title: "Google Maps Open URL",
      type: "url",
      description: "Direct Google Maps link for opening the location",
    }),
    defineField({
      name: "googleMapsDirectionsUrl",
      title: "Google Maps Directions URL",
      type: "url",
      description: "Google Maps directions link for the location",
    }),
    defineField({
      name: "contactEmail",
      title: "Contact Email",
      type: "string",
    }),
    defineField({
      name: "phone",
      title: "Phone Number",
      type: "string",
    }),
    defineField({
      name: "addressLine1",
      title: "Address Line 1",
      type: "string",
    }),
    defineField({
      name: "addressLine2",
      title: "Address Line 2",
      type: "string",
    }),
    defineField({
      name: "city",
      title: "City",
      type: "string",
    }),
    defineField({
      name: "country",
      title: "Country",
      type: "string",
    }),
    defineField({
      name: "postalCode",
      title: "Postal Code",
      type: "string",
    }),
    defineField({
      name: "linkedinUrl",
      title: "LinkedIn URL",
      type: "url",
    }),
    defineField({
      name: "instagramUrl",
      title: "Instagram URL",
      type: "url",
    }),
    defineField({
      name: "footerCompanyHeading",
      title: "Footer — Company Heading",
      type: "string",
      description: 'e.g. "Company"',
    }),
    defineField({
      name: "footerProductsHeading",
      title: "Footer — Products Heading",
      type: "string",
      description: 'e.g. "Products"',
    }),
    defineField({
      name: "footerContactHeading",
      title: "Footer — Contact Heading",
      type: "string",
      description: 'e.g. "Contact"',
    }),
    defineField({
      name: "footerContactLinkLabel",
      title: "Footer — Bottom Link Label",
      type: "string",
      description: 'e.g. "Contact Us"',
    }),
    defineField({
      name: "footerCopyrightSuffix",
      title: "Footer — Copyright Suffix",
      type: "string",
      description: 'Text shown after the site name, e.g. "All rights reserved."',
    }),
  ],
  preview: {
    prepare() {
      return { title: "Site Settings" };
    },
  },
});
